name: Convert PDF to HTML and Publish to Github Pages

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Adding Bookmarks
      run: |
        sudo apt-get update
        sudo apt-get install -y python3
        python3 -m pip install pyPDF2
        # python3 addbookmark.py

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Pull pdf2htmlEX Docker image
      run: docker pull pdf2htmlex/pdf2htmlex:0.18.8.rc2-master-20200820-alpine-3.12.0-x86_64

    - name: Convert PDF to HTML
      run: |
        for pdf in manuals/*.pdf; do
          echo "Processing file: $pdf"
          pdf_basename=$(basename "$pdf" .pdf)
          docker run --rm -v "$(pwd)/manuals:/pdf" -w /pdf pdf2htmlex/pdf2htmlex:0.18.8.rc2-master-20200820-alpine-3.12.0-x86_64 --zoom 1.3 --external-hint-tool=ttfautohint --embed-css 0 "$(basename "$pdf")" "${pdf_basename}.html"
        done

    - name: Check file permissions
      run: ls -l manuals

    - name: Change file ownership and permissions
      run: |
        sudo chown -R $USER:$USER manuals
        sudo chmod -R 755 manuals

    - name: Add home cover links
      run: python3 add_menus.py
    
    - name: Generate index.html
      run: |
        python3 generate_index.py

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    
    - name: Create or Checkout gh-pages branch
      run: |
        if git show-ref --verify --quiet refs/heads/gh-pages; then
          git checkout gh-pages
        else
          git checkout -b gh-pages
        fi
    
    - name: Checkout HTML files
      run: |
        if [ -d "manuals" ]; then
          mv manuals/*.html . || true
          mv manuals/*.css . || true
          git checkout main -- fancy.min.css || true
          rm -rf manuals .github *.py
        else
          echo "No HTML files to move"
        fi
    
    - name: Commit changes
      run: |
        git add .
        if [[ `git status --porcelain` ]]; then
          git commit -m 'Added new manual'
        fi
  
    - name: Push to gh-pages
      run: |
        git push origin gh-pages --force
